### ISSUE TITLE
how to set a default layout 

### ISSUE THREAD

**Issue by caelum29** [dkandalov/ijkl-shortcuts-plugin#7]
hi there! I need to restore the initial behavior of Option + L and Option + J. how to do this? deletion of the plugin does not help at all (( and changing of a keyboard layout (

**Comment by dkandalov** [comment]
Hi. 
Did you restart IDE after uninstalling the plugin? 
I'm not sure what you mean by "changing of a keyboard layout". From which layout to which? But in any case, if you switch to the original one, it definitely works (or it's a macos bug 🤔).
